package com.lavasoft;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-05-31T17:03:55.188+07:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://lavasoft.com/", name = "GeoIPServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface GeoIPServiceSoap {

    /**
     * <br/>Get Country and State XML String for a given ip address in x.x.x.x format<br/><br/>Parameter:GetIpAddress address &nbsp;&nbsp;&nbsp;&nbsp;<b>Type:String</b><br/><br/>Return:format in XML < GeoIP >< Country >US< /Country >< State >PA< /State >< /GeoIP > &nbsp;&nbsp;&nbsp;&nbsp;<b>Type:String</b>
     */
    @WebMethod(operationName = "GetIpLocation", action = "http://lavasoft.com/GetIpLocation")
    @RequestWrapper(localName = "GetIpLocation", targetNamespace = "http://lavasoft.com/", className = "com.lavasoft.GetIpLocation")
    @ResponseWrapper(localName = "GetIpLocationResponse", targetNamespace = "http://lavasoft.com/", className = "com.lavasoft.GetIpLocationResponse")
    @WebResult(name = "GetIpLocationResult", targetNamespace = "http://lavasoft.com/")
    public java.lang.String getIpLocation(

        @WebParam(name = "sIp", targetNamespace = "http://lavasoft.com/")
        java.lang.String sIp
    );
}
